"""
IVGS v5 — Quality Gate Workflow Service
==========================================

Quality gate workflow per §11.3.

Workflow:
1. Asset generated by pipeline stage.
2. validate_asset_quality_task runs automatically (enqueued by stage
   completion callback).
3. If approved: asset proceeds to next pipeline stage.
4. If flagged: asset added to Quality Review Queue in dashboard;
   pipeline pauses for that scene until human decision.
5. If rejected: regeneration queued automatically (max 2 regeneration
   attempts before escalating to flagged).
6. If regeneration also fails quality gate: added to DLQ with category
   'external' (generation model quality issue).

Projects cannot advance to composition until all scene assets have
decision = approved or explicit human override per §11.3.

Redis key structure:
- qg:asset:{asset_id}              — Hash with quality gate state
- qg:project:{project_id}:pending  — Set of pending asset IDs
- qg:project:{project_id}:flagged  — Set of flagged asset IDs
- qg:regeneration:{asset_id}       — Counter of regeneration attempts
"""

from __future__ import annotations

import json
import time
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Set

import redis.asyncio as aioredis
import structlog

from services.quality_validator import QualityDecision, QualityReport

logger = structlog.get_logger(__name__)


# ---------------------------------------------------------------------------
# Constants per §11.3
# ---------------------------------------------------------------------------

MAX_REGENERATION_ATTEMPTS = 2
DLQ_CATEGORY_EXTERNAL = "external"


# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------

class GateAction(str, Enum):
    """Actions taken by the quality gate."""

    PROCEED = "proceed"
    PAUSE = "pause"
    REGENERATE = "regenerate"
    ESCALATE_DLQ = "escalate_dlq"
    HUMAN_OVERRIDE = "human_override"


@dataclass
class GateDecision:
    """Decision made by the quality gate for an asset."""

    asset_id: str
    project_id: str
    scene_id: Optional[str]
    quality_decision: QualityDecision
    gate_action: GateAction
    regeneration_attempt: int
    max_regenerations: int
    message: str
    decided_at: str


@dataclass
class ProjectGateStatus:
    """Quality gate status for an entire project."""

    project_id: str
    total_assets: int
    approved_count: int
    flagged_count: int
    rejected_count: int
    pending_count: int
    can_advance: bool
    flagged_asset_ids: List[str]
    pending_asset_ids: List[str]
    human_overrides: List[str]


# ---------------------------------------------------------------------------
# Quality Gate Service
# ---------------------------------------------------------------------------

class QualityGateService:
    """
    Quality gate workflow enforcement per §11.3.

    Manages the quality gate for all generated assets, enforcing
    the approved/flagged/rejected workflow with automatic regeneration
    and escalation to DLQ.

    Args:
        redis: Redis connection for gate state.
        max_regeneration_attempts: Max regeneration attempts per §11.3 (default: 2).
        regeneration_callback: Async callable to trigger asset regeneration.
        dlq_callback: Async callable to route failed assets to DLQ.
    """

    # Redis key prefixes
    ASSET_PREFIX = "qg:asset:"
    PROJECT_PENDING_PREFIX = "qg:project_pending:"
    PROJECT_FLAGGED_PREFIX = "qg:project_flagged:"
    PROJECT_APPROVED_PREFIX = "qg:project_approved:"
    PROJECT_OVERRIDES_PREFIX = "qg:project_overrides:"
    REGENERATION_PREFIX = "qg:regeneration:"
    ASSET_HISTORY_PREFIX = "qg:history:"

    def __init__(
        self,
        redis: aioredis.Redis,
        max_regeneration_attempts: int = MAX_REGENERATION_ATTEMPTS,
        regeneration_callback: Optional[Callable] = None,
        dlq_callback: Optional[Callable] = None,
    ) -> None:
        self._redis = redis
        self._max_regeneration = max_regeneration_attempts
        self._regeneration_callback = regeneration_callback
        self._dlq_callback = dlq_callback

    async def process_quality_report(
        self,
        report: QualityReport,
    ) -> GateDecision:
        """
        Process a quality validation report through the gate per §11.3.

        Workflow:
        - approved → proceed to next stage
        - flagged → pause pipeline, add to review queue
        - rejected → regenerate (up to 2 attempts) → escalate

        Args:
            report: QualityReport from QualityValidator.

        Returns:
            GateDecision describing the action taken.
        """
        log = logger.bind(
            asset_id=report.asset_id,
            project_id=report.project_id,
            quality_decision=report.overall_decision.value,
        )
        log.info("quality_gate_processing")

        decision = report.overall_decision
        asset_id = report.asset_id
        project_id = report.project_id

        # Get current regeneration attempt count
        regen_key = f"{self.REGENERATION_PREFIX}{asset_id}"
        regen_count = int(await self._redis.get(regen_key) or "0")

        # --- Determine gate action ---
        if decision == QualityDecision.APPROVED:
            gate_action = GateAction.PROCEED
            await self._mark_approved(asset_id, project_id)
            message = "Asset approved — proceeding to next pipeline stage"

        elif decision == QualityDecision.FLAGGED:
            gate_action = GateAction.PAUSE
            await self._mark_flagged(asset_id, project_id, report)
            message = (
                "Asset flagged for human review — pipeline paused for this scene. "
                "Added to Quality Review Queue in dashboard."
            )

        elif decision == QualityDecision.REJECTED:
            if regen_count < self._max_regeneration:
                # Attempt regeneration per §11.3 step 5
                gate_action = GateAction.REGENERATE
                regen_count += 1
                await self._redis.set(regen_key, str(regen_count))
                await self._redis.expire(regen_key, 86400)  # 24h TTL

                message = (
                    f"Asset rejected — regeneration queued "
                    f"(attempt {regen_count}/{self._max_regeneration})"
                )

                # Trigger regeneration
                if self._regeneration_callback:
                    await self._regeneration_callback(
                        asset_id=asset_id,
                        project_id=project_id,
                        scene_id=report.scene_id,
                        asset_type=report.asset_type.value,
                        attempt=regen_count,
                    )

                log.info(
                    "regeneration_queued",
                    attempt=regen_count,
                    max_attempts=self._max_regeneration,
                )
            else:
                # Max regeneration attempts exceeded per §11.3 step 6
                gate_action = GateAction.ESCALATE_DLQ
                message = (
                    f"Asset rejected after {regen_count} regeneration attempts — "
                    f"escalating to DLQ with category '{DLQ_CATEGORY_EXTERNAL}' "
                    f"(generation model quality issue)"
                )

                # Route to DLQ
                if self._dlq_callback:
                    await self._dlq_callback(
                        asset_id=asset_id,
                        project_id=project_id,
                        scene_id=report.scene_id,
                        category=DLQ_CATEGORY_EXTERNAL,
                        reason=message,
                        quality_report=report.to_dict(),
                    )

                # Also mark as flagged for human visibility
                await self._mark_flagged(asset_id, project_id, report)

                log.warning(
                    "asset_escalated_to_dlq",
                    regen_attempts=regen_count,
                    category=DLQ_CATEGORY_EXTERNAL,
                )
        else:
            gate_action = GateAction.PROCEED
            message = "Unknown decision — defaulting to proceed"

        # --- Store gate decision ---
        gate_decision = GateDecision(
            asset_id=asset_id,
            project_id=project_id,
            scene_id=report.scene_id,
            quality_decision=decision,
            gate_action=gate_action,
            regeneration_attempt=regen_count,
            max_regenerations=self._max_regeneration,
            message=message,
            decided_at=datetime.now(timezone.utc).isoformat(),
        )

        await self._store_gate_decision(gate_decision, report)

        log.info(
            "quality_gate_decision",
            action=gate_action.value,
            regen_attempt=regen_count,
        )

        return gate_decision

    async def _mark_approved(
        self, asset_id: str, project_id: str
    ) -> None:
        """Mark an asset as approved and remove from pending/flagged."""
        pipe = self._redis.pipeline()
        pipe.sadd(f"{self.PROJECT_APPROVED_PREFIX}{project_id}", asset_id)
        pipe.srem(f"{self.PROJECT_PENDING_PREFIX}{project_id}", asset_id)
        pipe.srem(f"{self.PROJECT_FLAGGED_PREFIX}{project_id}", asset_id)
        pipe.hset(
            f"{self.ASSET_PREFIX}{asset_id}",
            mapping={
                "status": "approved",
                "updated_at": datetime.now(timezone.utc).isoformat(),
            },
        )
        await pipe.execute()

    async def _mark_flagged(
        self,
        asset_id: str,
        project_id: str,
        report: QualityReport,
    ) -> None:
        """Mark an asset as flagged for human review."""
        pipe = self._redis.pipeline()
        pipe.sadd(f"{self.PROJECT_FLAGGED_PREFIX}{project_id}", asset_id)
        pipe.srem(f"{self.PROJECT_PENDING_PREFIX}{project_id}", asset_id)
        pipe.hset(
            f"{self.ASSET_PREFIX}{asset_id}",
            mapping={
                "status": "flagged",
                "quality_report": json.dumps(report.to_dict()),
                "updated_at": datetime.now(timezone.utc).isoformat(),
            },
        )
        await pipe.execute()

    async def _store_gate_decision(
        self,
        decision: GateDecision,
        report: QualityReport,
    ) -> None:
        """Store gate decision for audit trail."""
        history_key = f"{self.ASSET_HISTORY_PREFIX}{decision.asset_id}"
        entry = {
            "action": decision.gate_action.value,
            "quality_decision": decision.quality_decision.value,
            "regeneration_attempt": decision.regeneration_attempt,
            "decided_at": decision.decided_at,
            "message": decision.message,
        }

        await self._redis.rpush(history_key, json.dumps(entry))
        await self._redis.expire(history_key, 604800)  # 7-day retention

    async def apply_human_override(
        self,
        asset_id: str,
        project_id: str,
        override_decision: str,
        reviewer_id: str,
        notes: Optional[str] = None,
    ) -> GateDecision:
        """
        Apply a human override decision per §11.3 step 4.

        Allows a human reviewer to approve or reject a flagged asset,
        overriding the automated quality gate decision.

        Args:
            asset_id: Asset identifier.
            project_id: Project identifier.
            override_decision: 'approve' or 'reject'.
            reviewer_id: ID of the human reviewer.
            notes: Optional reviewer notes.

        Returns:
            GateDecision with the override action.
        """
        log = logger.bind(
            asset_id=asset_id,
            project_id=project_id,
            override=override_decision,
            reviewer=reviewer_id,
        )
        log.info("human_override_applied")

        if override_decision == "approve":
            await self._mark_approved(asset_id, project_id)
            await self._redis.sadd(
                f"{self.PROJECT_OVERRIDES_PREFIX}{project_id}", asset_id
            )
            gate_action = GateAction.HUMAN_OVERRIDE
            message = f"Human override: approved by {reviewer_id}"
            quality_decision = QualityDecision.APPROVED
        else:
            gate_action = GateAction.ESCALATE_DLQ
            message = f"Human override: rejected by {reviewer_id}"
            quality_decision = QualityDecision.REJECTED

            if self._dlq_callback:
                await self._dlq_callback(
                    asset_id=asset_id,
                    project_id=project_id,
                    scene_id=None,
                    category=DLQ_CATEGORY_EXTERNAL,
                    reason=f"Rejected by human reviewer {reviewer_id}: {notes or 'no notes'}",
                )

        decision = GateDecision(
            asset_id=asset_id,
            project_id=project_id,
            scene_id=None,
            quality_decision=quality_decision,
            gate_action=gate_action,
            regeneration_attempt=0,
            max_regenerations=self._max_regeneration,
            message=message,
            decided_at=datetime.now(timezone.utc).isoformat(),
        )

        # Store override in history
        history_key = f"{self.ASSET_HISTORY_PREFIX}{asset_id}"
        entry = {
            "action": gate_action.value,
            "quality_decision": quality_decision.value,
            "reviewer_id": reviewer_id,
            "notes": notes,
            "decided_at": decision.decided_at,
            "message": message,
        }
        await self._redis.rpush(history_key, json.dumps(entry))

        return decision

    async def check_project_gate(
        self, project_id: str
    ) -> ProjectGateStatus:
        """
        Check if a project can advance to composition per §11.3.

        Projects cannot advance to composition until all scene assets
        have decision = approved or explicit human override.

        Args:
            project_id: Project identifier.

        Returns:
            ProjectGateStatus with gate readiness information.
        """
        approved = await self._redis.smembers(
            f"{self.PROJECT_APPROVED_PREFIX}{project_id}"
        )
        flagged = await self._redis.smembers(
            f"{self.PROJECT_FLAGGED_PREFIX}{project_id}"
        )
        pending = await self._redis.smembers(
            f"{self.PROJECT_PENDING_PREFIX}{project_id}"
        )
        overrides = await self._redis.smembers(
            f"{self.PROJECT_OVERRIDES_PREFIX}{project_id}"
        )

        approved_set = set(approved)
        flagged_set = set(flagged) - approved_set  # Overrides move to approved
        pending_set = set(pending) - approved_set - flagged_set

        total = len(approved_set) + len(flagged_set) + len(pending_set)
        can_advance = len(flagged_set) == 0 and len(pending_set) == 0 and total > 0

        status = ProjectGateStatus(
            project_id=project_id,
            total_assets=total,
            approved_count=len(approved_set),
            flagged_count=len(flagged_set),
            rejected_count=0,
            pending_count=len(pending_set),
            can_advance=can_advance,
            flagged_asset_ids=list(flagged_set),
            pending_asset_ids=list(pending_set),
            human_overrides=list(overrides),
        )

        logger.debug(
            "project_gate_checked",
            project_id=project_id,
            can_advance=can_advance,
            approved=len(approved_set),
            flagged=len(flagged_set),
            pending=len(pending_set),
        )

        return status

    async def register_asset(
        self,
        asset_id: str,
        project_id: str,
        asset_type: str,
        scene_id: Optional[str] = None,
    ) -> None:
        """
        Register a new asset for quality gate tracking.

        Called when an asset generation stage begins.

        Args:
            asset_id: Asset identifier.
            project_id: Project identifier.
            asset_type: Type of asset.
            scene_id: Scene identifier.
        """
        pipe = self._redis.pipeline()
        pipe.sadd(f"{self.PROJECT_PENDING_PREFIX}{project_id}", asset_id)
        pipe.hset(
            f"{self.ASSET_PREFIX}{asset_id}",
            mapping={
                "asset_id": asset_id,
                "project_id": project_id,
                "asset_type": asset_type,
                "scene_id": scene_id or "",
                "status": "pending",
                "registered_at": datetime.now(timezone.utc).isoformat(),
            },
        )
        await pipe.execute()

    async def get_asset_history(
        self, asset_id: str
    ) -> List[Dict[str, Any]]:
        """
        Get the quality gate history for an asset.

        Returns:
            List of historical gate decisions.
        """
        history_key = f"{self.ASSET_HISTORY_PREFIX}{asset_id}"
        entries = await self._redis.lrange(history_key, 0, -1)
        return [json.loads(e) for e in entries]

    async def get_review_queue(
        self, project_id: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """
        Get all flagged assets awaiting human review.

        Args:
            project_id: Optional filter by project.

        Returns:
            List of flagged asset details.
        """
        flagged_assets: List[Dict[str, Any]] = []

        if project_id:
            asset_ids = await self._redis.smembers(
                f"{self.PROJECT_FLAGGED_PREFIX}{project_id}"
            )
            for asset_id in asset_ids:
                data = await self._redis.hgetall(
                    f"{self.ASSET_PREFIX}{asset_id}"
                )
                if data and data.get("status") == "flagged":
                    flagged_assets.append(data)
        else:
            # Scan all projects (expensive, but needed for dashboard)
            async for key in self._redis.scan_iter(
                f"{self.PROJECT_FLAGGED_PREFIX}*"
            ):
                pid = key.replace(self.PROJECT_FLAGGED_PREFIX, "")
                asset_ids = await self._redis.smembers(key)
                for asset_id in asset_ids:
                    data = await self._redis.hgetall(
                        f"{self.ASSET_PREFIX}{asset_id}"
                    )
                    if data and data.get("status") == "flagged":
                        data["project_id"] = pid
                        flagged_assets.append(data)

        return flagged_assets
