"""
ORM model for the ``assets`` table (§4.1 Table 4).

Migration: 0001_initial_core

WP-56 Task 1 (ledger P2.60). MOVED here from ``ivgs-api/app/models/asset.py``.

The worker image ships ``shared/`` (``ivgs-workers/Dockerfile:30``) and does
NOT ship ``ivgs-api/``. Five worker call sites deferred-imported
``ivgs_api.app.models`` -- a package that resolves in no image -- so every one
of them raised ``ModuleNotFoundError`` at the moment it was reached. DLQ replay
was the visible casualty: ``process_dlq`` got as far as ``_dlq_table()`` and
died there.

Ruled a MOVE rather than an HTTP rewrite (WP-56 Task 1): the DLQ is the
mechanism reached for when things are already failing, and putting a network
hop inside a recovery path adds a way for the recovery itself to fail.

``shared.database.Base`` was already the declarative base for this model, so
the move is a relocation, not a re-parenting. ``app.models`` re-exports the
class, which keeps Alembic autogenerate, ``Base.metadata.create_all()`` and
every existing ``from app.models import ...`` working unchanged.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from typing import Optional

from sqlalchemy import (
    String, BigInteger, Float, Integer, Boolean,
    DateTime, ForeignKey, text,
)
from sqlalchemy.dialects.postgresql import UUID, ENUM as PG_ENUM, JSONB
from sqlalchemy.orm import Mapped, mapped_column

from shared.database import Base


class Asset(Base):
    __tablename__ = "assets"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("uuid_generate_v4()"),
    )
    project_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("projects.id", ondelete="CASCADE"),
        nullable=False,
    )
    scene_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("storyboard_scenes.id", ondelete="SET NULL"),
        nullable=True,
    )
    asset_type: Mapped[str] = mapped_column(
        PG_ENUM("image", "video", "audio", "document", "talking_head",
                "final_render", "reference_clip", name="asset_type", create_type=False),
        nullable=False,
        doc="PostgreSQL ENUM asset_type",
    )
    seaweedfs_fid: Mapped[Optional[str]] = mapped_column(
        String(255), nullable=True,
    )
    seaweedfs_path: Mapped[Optional[str]] = mapped_column(
        String(1024), nullable=True,
    )
    mime_type: Mapped[Optional[str]] = mapped_column(
        String(128), nullable=True,
    )
    file_size_bytes: Mapped[Optional[int]] = mapped_column(
        BigInteger, nullable=True,
    )
    duration_seconds: Mapped[Optional[float]] = mapped_column(
        Float, nullable=True,
    )
    language_code: Mapped[Optional[str]] = mapped_column(
        String(10), nullable=True,
    )
    generation_prompt_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("prompts.id", ondelete="SET NULL"),
        nullable=True,
    )
    # v4 tier columns
    storage_tier: Mapped[str] = mapped_column(
        PG_ENUM("hot", "warm", "cold", "archived", "deleted",
                name="storage_tier", create_type=False),
        nullable=False, server_default="hot",
        doc="PostgreSQL ENUM storage_tier",
    )
    tier_transition_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    preserve_flag: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("false"),
    )
    last_accessed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    content_hash: Mapped[Optional[str]] = mapped_column(
        String(64), nullable=True,
    )
    reference_count: Mapped[int] = mapped_column(
        Integer, nullable=False, server_default=text("1"),
    )
    generation_params_hash: Mapped[Optional[str]] = mapped_column(
        String(64), nullable=True,
    )
    # WP-45 Task 1 / migration 0028. Per-asset generation provenance: the engine,
    # the model, the prompt id, the input asset ids, the parameters. Every media
    # task in the fleet already sent this and the upload route discarded it
    # (WP-46 addendum A5.2, ledger L-7), so how a given clip was made was
    # unrecoverable the moment the worker log rotated.
    generation_metadata: Mapped[Optional[dict]] = mapped_column(
        JSONB, nullable=True,
    )
    # WP-56 Task 2 / migration 0030. AD-09.4.2 reference-don't-copy: a project
    # consuming a library asset records its ORIGIN here instead of duplicating
    # the binary, which is what makes a logo swap a reference change rather
    # than a re-upload. NULL for every asset generated by the pipeline.
    #
    # The worker image carries this column because it carries this model, but
    # NO worker code reads it and none may before the Temporal cutover — that
    # is WP-56's boundary condition. `library_assets` itself is deliberately
    # absent from `shared/models/`.
    #
    # ORDERING NOTE FOR DEPLOYS: migration 0030 must be applied BEFORE a worker
    # image carrying this class is started, or `select(Asset)` raises
    # UndefinedColumn against the old schema.
    library_asset_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("library_assets.id", ondelete="SET NULL"),
        nullable=True,
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )

    def __repr__(self) -> str:
        return (
            f"<Asset id={self.id} type={self.asset_type} "
            f"project={self.project_id}>"
        )
