"""
Storyboard scene Pydantic schemas per §5.1.4.

Includes: SceneCreate, SceneUpdate, SceneResponse, SceneReorderRequest.
"""
from datetime import datetime
from typing import Any, Dict, List, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator

# WP-43 D-2, RULED EXTEND. The Edit Scene modal has always sent nine keys;
# SceneUpdate declared four, and Pydantic drops what a model does not declare -
# silently, with a 200. So camera_angle, transition_type, effects,
# timing_offset_ms and generation_params were serialised, sent, and discarded,
# and the dialog looked exactly as though it had saved them. WP-43 could only
# label them "Not saved to the server" from the frontend; migration 0028 gives
# them columns and this gives them a schema.
#
# The operator ruling was EXTEND rather than remove, and the reason is on the
# record: camera_angle and transition_type are read by the generation and
# composition prompts, so deleting the controls would discard intent the
# operator is already expressing.
MAX_EFFECTS = 32
MAX_EFFECT_NAME = 64
# +/- 60 seconds. A timing offset is a nudge against the narration; anything
# larger is a duration change or a reorder, and both have their own controls.
MAX_TIMING_OFFSET_MS = 60_000
# WP-IVGS-10. A rationale is one line. The cap is generous enough for a real
# sentence and small enough that a model which starts writing an essay into the
# column is refused rather than storing one.
MAX_MEDIA_RATIONALE = 500


#: WP-68. Re-exported from ONE definition (`shared.models.enums.MEDIA_TYPES`),
#: read by both validators below AND by the ORM column. They were three
#: separate literal lists -- two validators and the model -- so a fourth value
#: had to be added in three places, and missing the third let a row be written
#: that could not be read back.
from shared.models.enums import MEDIA_TYPES  # noqa: E402

#: WP-IVGS-10. Read from the completeness module rather than restated, for the
#: same reason MEDIA_TYPES is: three literal lists is how a fourth value gets
#: added to two of them.
from app.services.storyboard_completeness import TEXT_CARRIERS  # noqa: E402
from shared.models.enums import BLOOM_LEVELS, INSTRUCTIONAL_EVENTS  # noqa: E402


class SceneCreate(BaseModel):
    """Schema for creating a storyboard scene (typically auto-generated by pipeline)."""

    scene_index: int = Field(ge=0)
    narration_text: Optional[str] = None
    visual_description: Optional[str] = None
    media_type: Optional[str] = Field(default=None, description="image | video_clip | animation")
    duration_seconds: Optional[float] = Field(default=None, ge=0.1, le=600.0)

    camera_angle: Optional[str] = Field(
        default=None, max_length=64,
        description="Camera framing for this scene, e.g. wide, close-up.",
    )
    transition_type: Optional[str] = Field(
        default=None, max_length=64,
        description="Transition into this scene, e.g. cut, fade, dissolve.",
    )
    effects: Optional[List[str]] = Field(
        default=None,
        description="Effect identifiers applied to this scene.",
    )
    timing_offset_ms: Optional[int] = Field(
        default=None,
        ge=-MAX_TIMING_OFFSET_MS,
        le=MAX_TIMING_OFFSET_MS,
        description="Millisecond nudge of this scene against the narration.",
    )
    generation_params: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Per-scene generation overrides (seed, steps, guidance...).",
    )

    # ── WP-IVGS-10, v7's per-scene content contract (migration 0045) ──
    media_rationale: Optional[str] = Field(
        default=None, max_length=MAX_MEDIA_RATIONALE,
        description=(
            "v7 RULE 9: one line saying why THIS media_type for THIS scene. "
            "Free text, read by a human at the storyboard gate."
        ),
    )
    text_carried_by: Optional[str] = Field(
        default=None,
        description=(
            "v7 RULE 1-EXTENDED. Set to 'narration' to DECLARE that this "
            "scene's written or numeric content is carried by the spoken "
            "narration while the visual depicts the non-text situation. The "
            "only alternative answer is to author the scene as "
            "motion_graphics with a template. Absent means no declaration."
        ),
    )

    @field_validator("text_carried_by")
    @classmethod
    def validate_text_carried_by(cls, v: Optional[str]) -> Optional[str]:
        """Refuse an unknown carrier rather than storing it.

        The database CHECK would refuse it too, but as a 500 out of the driver.
        A declaration whose value nobody recognises is worse than no
        declaration: it looks like an answer at the gate and satisfies nothing.
        """
        if v is None:
            return v
        cleaned = v.strip().lower()
        if cleaned not in TEXT_CARRIERS:
            raise ValueError(
                f"text_carried_by must be one of: {', '.join(TEXT_CARRIERS)}. "
                f"It is a declaration that the narration carries this scene's "
                f"written content, not free text."
            )
        return cleaned

    @field_validator("effects")
    @classmethod
    def validate_effects(cls, v: Optional[List[str]]) -> Optional[List[str]]:
        """Inline, worded the way the server words its other refusals (WP-43)."""
        if v is None:
            return v
        if len(v) > MAX_EFFECTS:
            raise ValueError(
                f"At most {MAX_EFFECTS} effects per scene; got {len(v)}."
            )
        cleaned = []
        for item in v:
            if not isinstance(item, str):
                raise ValueError("Each effect must be a string identifier.")
            name = item.strip()
            if not name:
                raise ValueError("An effect identifier cannot be blank.")
            if len(name) > MAX_EFFECT_NAME:
                raise ValueError(
                    f"Effect identifier is longer than {MAX_EFFECT_NAME} "
                    f"characters: {name[:32]}..."
                )
            cleaned.append(name)
        return cleaned

    @field_validator("media_type")
    @classmethod
    def validate_media_type(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and v not in MEDIA_TYPES:
            raise ValueError(
                f"media_type must be one of: {', '.join(MEDIA_TYPES)}"
            )
        return v

    # ── WP-IVGS-12, the Design Contract (migration 0048) ──
    # Accepted here so a scene can be created or corrected WITH its
    # declarations by any caller — the gate's editor, a test, a future
    # whole-storyboard write. The pipeline's own path does not use them: the
    # frozen stage body POSTs five keys plus three, and the declarations
    # arrive by the design-brief seam instead.
    serves_outcomes: Optional[List[str]] = Field(
        default=None,
        description="Outcome ids this scene serves. At least one, once a design brief exists.",
    )
    instructional_event: Optional[str] = Field(
        default=None,
        description="Gagné event (Foundation §3): " + " | ".join(INSTRUCTIONAL_EVENTS),
    )
    bloom_level: Optional[str] = Field(
        default=None,
        description="Bloom level (Foundation §2): " + " | ".join(BLOOM_LEVELS),
    )
    source_refs: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description=(
            "Character spans of transcripts.source_text this scene works from. "
            "Of source_text, NOT refined_text — stage 1 overwrites the latter."
        ),
    )
    scene_origin: Optional[str] = Field(
        default=None,
        description="'sourced' (with source_refs) XOR 'designed'. Enforced by CHECK.",
    )
    rewrite_of: Optional[Dict[str, Any]] = Field(
        default=None,
        description=(
            "{span, original, reason} when the narration was reworded. Ruling "
            "R1a: rewriting is permitted, silence is not."
        ),
    )
    signal_spec: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional Mayer signalling: {highlight, at_word}.",
    )

class SceneAdaptDescriptionRequest(BaseModel):
    """Body for POST /projects/{id}/scenes/{sid}/adapt-description. WP-64 Task 3.

    ``target_media_type`` is what the description should be rewritten FOR, and
    it is deliberately explicit rather than read off the scene row: the operator
    asks for the adaptation while the dropdown is changed and BEFORE they save,
    so the row still says what the scene used to be.
    """

    target_media_type: str = Field(
        description=(
            "The medium to write the description for: image, video_clip or "
            "animation."
        ),
    )

    @field_validator("target_media_type")
    @classmethod
    def validate_target(cls, v: str) -> str:
        from app.services.adaptation_service import MEDIA_TYPES

        value = (v or "").strip()
        if value not in MEDIA_TYPES:
            raise ValueError(
                f"Invalid target media type '{v}'. "
                f"Allowed: {', '.join(MEDIA_TYPES)}."
            )
        return value


class SceneAdaptDescriptionResponse(BaseModel):
    """The proposal, returned to the modal. NOT a record of a write.

    ``scene_written`` is in the payload and is always ``False``. It is there so
    the contract is legible from the response itself rather than from the
    documentation: this endpoint returns a suggestion for a human to read, edit
    and save, and the save is the existing PATCH.
    """

    scene_id: UUID
    scene_index: int
    current_media_type: str
    target_media_type: str
    current_description: str
    adapted_description: str
    prompt_version: int
    prompt_id: UUID
    model: str
    binding: str
    scene_written: bool = False
    generated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class SceneUpdate(BaseModel):
    """Schema for PATCH /api/v1/projects/{id}/scenes/{sid}.

    WP-45 Task 6(d) / WP-43 D-2: the five fields the modal has always sent are
    declared here for the first time. Until now they were dropped in silence.
    """

    narration_text: Optional[str] = None
    visual_description: Optional[str] = None
    media_type: Optional[str] = None
    duration_seconds: Optional[float] = Field(default=None, ge=0.1, le=600.0)

    camera_angle: Optional[str] = Field(
        default=None, max_length=64,
        description="Camera framing for this scene, e.g. wide, close-up.",
    )
    transition_type: Optional[str] = Field(
        default=None, max_length=64,
        description="Transition into this scene, e.g. cut, fade, dissolve.",
    )
    effects: Optional[List[str]] = Field(
        default=None,
        description="Effect identifiers applied to this scene.",
    )
    timing_offset_ms: Optional[int] = Field(
        default=None,
        ge=-MAX_TIMING_OFFSET_MS,
        le=MAX_TIMING_OFFSET_MS,
        description="Millisecond nudge of this scene against the narration.",
    )
    generation_params: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Per-scene generation overrides (seed, steps, guidance...).",
    )

    # ── WP-IVGS-10, v7's per-scene content contract (migration 0045) ──
    media_rationale: Optional[str] = Field(
        default=None, max_length=MAX_MEDIA_RATIONALE,
        description=(
            "v7 RULE 9: one line saying why THIS media_type for THIS scene. "
            "Free text, read by a human at the storyboard gate."
        ),
    )
    text_carried_by: Optional[str] = Field(
        default=None,
        description=(
            "v7 RULE 1-EXTENDED. Set to 'narration' to DECLARE that this "
            "scene's written or numeric content is carried by the spoken "
            "narration while the visual depicts the non-text situation. The "
            "only alternative answer is to author the scene as "
            "motion_graphics with a template. Absent means no declaration."
        ),
    )

    @field_validator("text_carried_by")
    @classmethod
    def validate_text_carried_by(cls, v: Optional[str]) -> Optional[str]:
        """Refuse an unknown carrier rather than storing it.

        The database CHECK would refuse it too, but as a 500 out of the driver.
        A declaration whose value nobody recognises is worse than no
        declaration: it looks like an answer at the gate and satisfies nothing.
        """
        if v is None:
            return v
        cleaned = v.strip().lower()
        if cleaned not in TEXT_CARRIERS:
            raise ValueError(
                f"text_carried_by must be one of: {', '.join(TEXT_CARRIERS)}. "
                f"It is a declaration that the narration carries this scene's "
                f"written content, not free text."
            )
        return cleaned

    @field_validator("effects")
    @classmethod
    def validate_effects(cls, v: Optional[List[str]]) -> Optional[List[str]]:
        """Inline, worded the way the server words its other refusals (WP-43)."""
        if v is None:
            return v
        if len(v) > MAX_EFFECTS:
            raise ValueError(
                f"At most {MAX_EFFECTS} effects per scene; got {len(v)}."
            )
        cleaned = []
        for item in v:
            if not isinstance(item, str):
                raise ValueError("Each effect must be a string identifier.")
            name = item.strip()
            if not name:
                raise ValueError("An effect identifier cannot be blank.")
            if len(name) > MAX_EFFECT_NAME:
                raise ValueError(
                    f"Effect identifier is longer than {MAX_EFFECT_NAME} "
                    f"characters: {name[:32]}..."
                )
            cleaned.append(name)
        return cleaned

    @field_validator("media_type")
    @classmethod
    def validate_media_type(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and v not in MEDIA_TYPES:
            raise ValueError(
                f"media_type must be one of: {', '.join(MEDIA_TYPES)}"
            )
        return v

    # ── WP-IVGS-12, the Design Contract (migration 0048) ──
    # Accepted here so a scene can be created or corrected WITH its
    # declarations by any caller — the gate's editor, a test, a future
    # whole-storyboard write. The pipeline's own path does not use them: the
    # frozen stage body POSTs five keys plus three, and the declarations
    # arrive by the design-brief seam instead.
    serves_outcomes: Optional[List[str]] = Field(
        default=None,
        description="Outcome ids this scene serves. At least one, once a design brief exists.",
    )
    instructional_event: Optional[str] = Field(
        default=None,
        description="Gagné event (Foundation §3): " + " | ".join(INSTRUCTIONAL_EVENTS),
    )
    bloom_level: Optional[str] = Field(
        default=None,
        description="Bloom level (Foundation §2): " + " | ".join(BLOOM_LEVELS),
    )
    source_refs: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description=(
            "Character spans of transcripts.source_text this scene works from. "
            "Of source_text, NOT refined_text — stage 1 overwrites the latter."
        ),
    )
    scene_origin: Optional[str] = Field(
        default=None,
        description="'sourced' (with source_refs) XOR 'designed'. Enforced by CHECK.",
    )
    rewrite_of: Optional[Dict[str, Any]] = Field(
        default=None,
        description=(
            "{span, original, reason} when the narration was reworded. Ruling "
            "R1a: rewriting is permitted, silence is not."
        ),
    )
    signal_spec: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional Mayer signalling: {highlight, at_word}.",
    )

class SceneBatchRegenerateRequest(BaseModel):
    """Body of POST /api/v1/projects/{id}/scenes/batch-regenerate.

    WP-63 Task 7. THIS ROUTE DID NOT EXIST. `useStoryboard.regenerateScenes`
    has POSTed to it since WP-38 -- it is what the "Regenerate Selected" button
    on the Storyboard tab calls -- and every press answered 404. The single
    scene route was built by WP-45 and works; its bulk sibling was never
    written, and nothing said so, because the frontend swallows the failure.

    `scene_ids` is a list rather than a count because the operator selects
    particular scenes; the recovery this package exists for is three named
    scene indexes out of nine, not "the first three".
    """

    scene_ids: List[UUID] = Field(min_length=1, max_length=200)


class SceneResponse(BaseModel):
    """Response schema for a storyboard scene."""

    id: UUID
    project_id: UUID
    scene_index: int
    narration_text: Optional[str] = None
    visual_description: Optional[str] = None
    media_type: Optional[str] = None
    duration_seconds: Optional[float] = None
    camera_angle: Optional[str] = None
    transition_type: Optional[str] = None
    effects: Optional[List[str]] = None
    timing_offset_ms: Optional[int] = None
    generation_params: Optional[Dict[str, Any]] = None
    # WP-IVGS-10: on the response because the gate UI shows them beside the
    # completeness flags, and because a declaration nobody can read back is not
    # auditable.
    media_rationale: Optional[str] = None
    text_carried_by: Optional[str] = None
    created_at: datetime
    updated_at: datetime


    # ── WP-IVGS-12, the Design Contract (migration 0048) ──
    # Accepted here so a scene can be created or corrected WITH its
    # declarations by any caller — the gate's editor, a test, a future
    # whole-storyboard write. The pipeline's own path does not use them: the
    # frozen stage body POSTs five keys plus three, and the declarations
    # arrive by the design-brief seam instead.
    serves_outcomes: Optional[List[str]] = Field(
        default=None,
        description="Outcome ids this scene serves. At least one, once a design brief exists.",
    )
    instructional_event: Optional[str] = Field(
        default=None,
        description="Gagné event (Foundation §3): " + " | ".join(INSTRUCTIONAL_EVENTS),
    )
    bloom_level: Optional[str] = Field(
        default=None,
        description="Bloom level (Foundation §2): " + " | ".join(BLOOM_LEVELS),
    )
    source_refs: Optional[List[Dict[str, Any]]] = Field(
        default=None,
        description=(
            "Character spans of transcripts.source_text this scene works from. "
            "Of source_text, NOT refined_text — stage 1 overwrites the latter."
        ),
    )
    scene_origin: Optional[str] = Field(
        default=None,
        description="'sourced' (with source_refs) XOR 'designed'. Enforced by CHECK.",
    )
    rewrite_of: Optional[Dict[str, Any]] = Field(
        default=None,
        description=(
            "{span, original, reason} when the narration was reworded. Ruling "
            "R1a: rewriting is permitted, silence is not."
        ),
    )
    signal_spec: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Optional Mayer signalling: {highlight, at_word}.",
    )

    model_config = ConfigDict(from_attributes=True)


class SceneReorderItem(BaseModel):
    """Single item in a scene reorder request."""

    id: UUID
    scene_index: int = Field(ge=1)


class SceneReorderRequest(BaseModel):
    """
    Schema for POST /api/v1/projects/{id}/scenes/reorder.

    Body: [{id, scene_index}, ...]
    """

    items: List[SceneReorderItem] = Field(min_length=1)

    @field_validator("items")
    @classmethod
    def validate_no_duplicates(cls, items: List[SceneReorderItem]) -> List[SceneReorderItem]:
        indices = [item.scene_index for item in items]
        if len(indices) != len(set(indices)):
            raise ValueError("Duplicate scene_index values are not allowed")
        ids = [item.id for item in items]
        if len(ids) != len(set(ids)):
            raise ValueError("Duplicate scene IDs are not allowed")
        return items
