"""
Storyboard scene Pydantic schemas per §5.1.4.

Includes: SceneCreate, SceneUpdate, SceneResponse, SceneReorderRequest.
"""
from datetime import datetime
from typing import List, Optional
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator


class SceneCreate(BaseModel):
    """Schema for creating a storyboard scene (typically auto-generated by pipeline)."""

    scene_index: int = Field(ge=1)
    narration_text: Optional[str] = None
    visual_description: Optional[str] = None
    media_type: Optional[str] = Field(default=None, description="image | video_clip | animation")
    duration_seconds: Optional[float] = Field(default=None, ge=0.1, le=600.0)

    @field_validator("media_type")
    @classmethod
    def validate_media_type(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and v not in ("image", "video_clip", "animation"):
            raise ValueError("media_type must be one of: image, video_clip, animation")
        return v


class SceneUpdate(BaseModel):
    """Schema for PATCH /api/v1/projects/{id}/scenes/{sid}."""

    narration_text: Optional[str] = None
    visual_description: Optional[str] = None
    media_type: Optional[str] = None
    duration_seconds: Optional[float] = Field(default=None, ge=0.1, le=600.0)

    @field_validator("media_type")
    @classmethod
    def validate_media_type(cls, v: Optional[str]) -> Optional[str]:
        if v is not None and v not in ("image", "video_clip", "animation"):
            raise ValueError("media_type must be one of: image, video_clip, animation")
        return v


class SceneResponse(BaseModel):
    """Response schema for a storyboard scene."""

    id: UUID
    project_id: UUID
    scene_index: int
    narration_text: Optional[str] = None
    visual_description: Optional[str] = None
    media_type: Optional[str] = None
    duration_seconds: Optional[float] = None
    created_at: datetime
    updated_at: datetime

    model_config = ConfigDict(from_attributes=True)


class SceneReorderItem(BaseModel):
    """Single item in a scene reorder request."""

    id: UUID
    scene_index: int = Field(ge=1)


class SceneReorderRequest(BaseModel):
    """
    Schema for POST /api/v1/projects/{id}/scenes/reorder.

    Body: [{id, scene_index}, ...]
    """

    items: List[SceneReorderItem] = Field(min_length=1)

    @field_validator("items")
    @classmethod
    def validate_no_duplicates(cls, items: List[SceneReorderItem]) -> List[SceneReorderItem]:
        indices = [item.scene_index for item in items]
        if len(indices) != len(set(indices)):
            raise ValueError("Duplicate scene_index values are not allowed")
        ids = [item.id for item in items]
        if len(ids) != len(set(ids)):
            raise ValueError("Duplicate scene IDs are not allowed")
        return items
